mylist = ()
# l1 = list(mylist)
# l1.insert(0,"Orange")
# l1.insert(1,"Apple")
# l1.insert(2,"Cherry")
# l1.insert(3,"Mango")
# l1.insert(4,"Banana")
# l1.insert(5,"Grapes")
# l1.insert(6,"Lemon")
# print(l1)
